### ISSUE TITLE
Alexa Volume is a string, expects a number

### ISSUE THREAD

**Issue by Grothesk242** [ticaki/DWD-UWZ-NINA-Pushwarnungen-iobroker#19]
Seit Kurzem meldet sich der javascript Adapter mit dieser Meldung, wenn das skript ausgelöst wird: 

```2022-07-11 22:18:31.090  - warn: javascript.0 (978) You are assigning a string to the state "alexa2.0.Echo-Devices.G090LV037337008G.Player.volume" which expects a number. Please fix your code to use a number or change the state type to string. This warning might become an error in future versions.
2022-07-11 22:18:31.093  - warn: javascript.0 (978)     at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1680:20)
2022-07-11 22:18:31.094  - warn: javascript.0 (978)     at Object.<anonymous> (script.js.common.dwd_uwz_nina_warnungen:2184:149)
2022-07-11 22:18:31.094  - warn: javascript.0 (978)     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2387:34)
2022-07-11 22:18:31.094  - warn: javascript.0 (978)     at listOnTimeout (node:internal/timers:564:17)
2022-07-11 22:18:31.094  - warn: javascript.0 (978)     at processTimers (node:internal/timers:507:7)
2022-07-11 22:18:31.125  - error: alexa2.0 (1054) Datatype for Echo-Devices.G090LV037337008G.Player.volume differs from expected, ignore state change! Please write correct datatype (number)

**Comment by toon2006** [comment]
ist leider bei mir auch der Fall.

**Comment by ticaki** [comment]
Ich sollte wohl öfter mal auf Github schauen, hat sich das Problem erledigt?

**Comment by Grothesk242** [comment]
Habe es länger nicht mehr beobachtet.
